Added Error handling

diff --git a/scripts/getsite b/scripts/getsite
--- a/scripts/getsite
+++ b/scripts/getsite
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -Eeuo pipefail
+trap "echo -e \"\033[1;31m[!] \e[0mScript error occured in $0.\"" ERR
 
 if [ $# == 0 ] ; then
     echo "Usage: getsite [URL]"
